### This is the main way to configure the application (other than annotations).
### This file is in Yaml format but can also configure spring boot using the traditional
### Java properties file format.

spring.jmx:
   enabled: false

spring.datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:mem:bootexample;MODE=MySQL

server:
  port: 8090

#todo: make sure to always enable security in production
security:
  basic:
    enabled: false

#management endpoints on a separate port
management:
  port: 8091
  security:
    enabled: false # management port is internal only. no need to secure it.


#default project info followed by actual injected pom-specified values.
project:
  name: Wikipedia
  version: 0.1
  description: A simple RESTful software service that will allow a merchant to create a new simple offer
info:
  build:
    artifact: ${project.artifactId}
    name: ${project.name}
    description: ${project.description}
    version: ${project.version}

wiki.service:
  name: 'default profile:'

---
spring:
  profiles: test
  h2:
    console:
      enabled: true

spring.jpa:
    hibernate.ddl-auto: create-drop

wiki.service:
  name: 'test profile:'

logging:
  file: wikipedia_offer.log
  org.hibernate: INFO